declare module '*.jpg';
declare module '*.jpeg';
declare module '*.gif';
declare module '*.png';
declare module '*.svg';
declare module '*.gif';
declare module '*.gif.mp4';
declare module '*.mp4';
declare module 'react-slick'
declare module "*.module.css";
declare module "react-router-hash-link"
declare module "react-image-mapper"